spring:
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  cloud:
    nacos:
      discovery:
        ip: 127.0.0.1
