package com.novamind.aigc.react.model;

import lombok.Builder;
import lombok.Data;

/**
 * Represents a single step in the ReAct execution cycle
 */
@Data
@Builder
public class ReActStep {
    /**
     * Step number in the execution sequence
     */
    private int stepNumber;
    
    /**
     * Reasoning thought generated by the LLM
     */
    private String thought;
    
    /**
     * Action decision made based on the thought
     */
    private ActionDecision action;
    
    /**
     * Observation from executing the action
     */
    private String observation;
    
    /**
     * Timestamp when this step was created
     */
    private long timestamp;
    
    /**
     * Current status of this step
     */
    private StepStatus status;
}
